version: '3.8'

services:
  web:
    build: .
    command: apache2ctl -D FOREGROUND
    volumes:
      - .:/app
      - static_volume:/app/public
      - media_volume:/app/media
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:6.2

volumes:
  mysql_data:
  static_volume:
  media_volume:
