version: '3.8'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/public
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:6.2

  nginx:
    image: nginx:1.21
    volumes:
      - static_volume:/app/public:ro
      - media_volume:/app/media:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume:
  media_volume:
