# Generated by Django 5.0.7 on 2024-08-04 22:25

import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=wagtail.fields.StreamField([('date', wagtail.blocks.DateBlock()), ('head', wagtail.blocks.StructBlock([('head_type', wagtail.blocks.ChoiceBlock(choices=[('h2', 'head 2'), ('h3', 'head 3'), ('h4', 'head 4')], max_length=2)), ('title', wagtail.blocks.CharBlock(max_length=255))])), ('blockquote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock())])), ('rich_text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'code', 'ol', 'ul', 'link', 'document-link'])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(max_length=50, required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('code', wagtail.blocks.StructBlock([('code_type', wagtail.blocks.ChoiceBlock(choices=[('py', 'Python'), ('js', 'Javascript'), ('java', 'Java'), ('html', 'html'), ('dart', 'Dart'), ('c', 'C')])), ('code', wagtail.blocks.TextBlock())]))]),
        ),
    ]
